[tool.poetry]
name = "buildh3r-june-algorand"
version = "0.1.0"
description = ""
authors = ["TheSpiritMan <sandabgc26@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
